### ISSUE TITLE
Missing mandatory attribute needs error message

### ISSUE THREAD

**Issue by cacraigucar** [gold2718/ccpp-framework#2]
When the mandatory attribute "intent" is missing the following is reported.  It doesn't give a hint of what is wrong.

-- Traceback (most recent call last):
  File "/home/cacraig/CPF_proto_new_cam_kessler/ccpp-framework/scripts/ccpp_capgen.py", line 271, in <module>
    _main_func()
  File "/home/cacraig/CPF_proto_new_cam_kessler/ccpp-framework/scripts/ccpp_capgen.py", line 247, in _main_func
    ccpp_api = API(sdfs, host_model, scheme_headers, logger)
  File "/home/cacraig/CPF_proto_new_cam_kessler/ccpp-framework/scripts/ccpp_suite.py", line 896, in __init__
    suite.analyze(host_model, scheme_headers, logger)
  File "/home/cacraig/CPF_proto_new_cam_kessler/ccpp-framework/scripts/ccpp_suite.py", line 767, in analyze
    item.analyze(phase, self, scheme_headers, logger)
  File "/home/cacraig/CPF_proto_new_cam_kessler/ccpp-framework/scripts/ccpp_suite.py", line 431, in analyze
    lschemes, lvars = item.analyze(phase, self, scheme_headers, suite_vars, logger)
  File "/home/cacraig/CPF_proto_new_cam_kessler/ccpp-framework/scripts/ccpp_suite.py", line 240, in analyze
    intent = svar.get_prop_value('intent').lower()
AttributeError: 'NoneType' object has no attribute 'lower'

CMake Error at CMakeLists.txt:140 (MESSAGE):
  CCPP cap generation FAILED: result = 1

**Comment by gold2718** [comment]
Fixed in 8271f60ebc81a186708780c3c60a5831847576c9 (not sure why PR did not close this).
