### ISSUE TITLE
Improve error message for incorrectly named index variable

### ISSUE THREAD

**Issue by cacraigucar** [gold2718/ccpp-framework#39]
It would be helpful (if it is easy to do) to include the incorrect name for the index variable.

The current error message is:
Parsing metadata_file, '/home/cacraig/CAMDEN_heldsuarez/src/dynamics/utils/vert_coord.meta'
Parsing file, physics_types, from registry
Traceback (most recent call last):
  File "/home/cacraig/CAMDEN_heldsuarez/cime_config/buildnml", line 293, in <module>
    _main_func()
  File "/home/cacraig/CAMDEN_heldsuarez/cime_config/buildnml", line 289, in _main_func
    buildnml(case, caseroot, "cam")
  File "/home/cacraig/CAMDEN_heldsuarez/cime_config/buildnml", line 127, in buildnml
    config.generate_cam_src(gen_indent)
  File "/home/cacraig/CAMDEN_heldsuarez/cime_config/cam_config.py", line 1022, in generate_cam_src
    dyn, gen_fort_indent)
  File "/home/cacraig/CAMDEN_heldsuarez/cime_config/cam_autogen.py", line 323, in generate_registry
    error_on_no_validate=True)
  File "/home/cacraig/CAMDEN_heldsuarez/src/data/generate_registry_data.py", line 1544, in gen_registry
    src_root, reg_dir, indent, logger)
  File "/home/cacraig/CAMDEN_heldsuarez/src/data/generate_registry_data.py", line 1421, in write_registry_files
    files.append(File(section, known_types, dycore, config, logger))
  File "/home/cacraig/CAMDEN_heldsuarez/src/data/generate_registry_data.py", line 1061, in __init__
    self.add_variable(obj, logger)
  File "/home/cacraig/CAMDEN_heldsuarez/src/data/generate_registry_data.py", line 1086, in add_variable
    logger)
  File "/home/cacraig/CAMDEN_heldsuarez/src/data/generate_registry_data.py", line 529, in __init__
    vdict))
  File "/home/cacraig/CAMDEN_heldsuarez/src/data/generate_registry_data.py", line 362, in __init__
    raise CCPPError(emsg.format(self.index_name, parent_name))
  File "/home/cacraig/CAMDEN_heldsuarez/src/data/generate_registry_data.py", line 313, in index_name
    return self.__index_name
AttributeError: 'ArrayElement' object has no attribute '_VarBase__index_name'
ERROR: /home/cacraig/CAMDEN_heldsuarez/cime_config/buildnml /home/cacraig/CAMDEN_heldsuarez/cime/scripts/test_camden_kessler_try06 FAILED, see above

**Comment by gold2718** [comment]
As you can see from the traceback, this error is occurring in the registry generator, not in the CCPP Framework. Please open this issue in the CAMDEN repo and close this issue.
Note, this is probably in internal bug -- even if this is due to a user data error, it is triggering an inappropriate response.
